### ISSUE TITLE
Table are not being generated

### ISSUE THREAD

**Issue by rathee** [UW-xDD/table-extract#7]
I tried with different pdfs but tables are not being generated. I  am facing this error:
Traceback (most recent call last):
  File "do_extract.py", line 19, in <module>
    extract_tables(arguments.doc_path)
  File "/home/rathee/projects/table-extract/table_extractor.py", line 280, in extract_tables
    doc_stats = summarize_document(area_stats)
  File "/home/rathee/projects/table-extract/table_extractor.py", line 141, in summarize_document
    'line_height_avg': np.nanmean([a for a in area['line_heights'] for area in area_stats]),
UnboundLocalError: local variable 'area' referenced before assignment

**Comment by vlall** [comment]
How did you fix this?
