### ISSUE TITLE
The numpy requirement should be version 1.14.2

### ISSUE THREAD

**Issue by GrazingScientist** [UW-xDD/table-extract#9]
When I run on the numpy version 1.10.4 on my Mac, as given by the requirement, the script fails with

> RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "annotate.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/usr/local/lib/python3.6/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/usr/local/lib/python3.6/site-packages/matplotlib/artist.py", line 15, in <module>
    from .transforms import (Bbox, IdentityTransform, TransformedBbox,
  File "/usr/local/lib/python3.6/site-packages/matplotlib/transforms.py", line 39, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
ImportError: numpy.core.multiarray failed to import

However, when running first

`pip install -U numpy`

It upgrades to 1.14.2 (at the time of writing) and the script runs without this error.

**Comment by jczaplew** [comment]
Fixed in 123d014
